name: movie_library
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  carousel_slider: ^5.0.0
  firebase_storage: ^12.4.6
  flutter_bloc: ^9.1.1
  provider: ^6.1.5
  go_router: ^16.0.0
  lottie: ^3.3.1
  image_picker: ^1.0.4
  image_cropper: ^9.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cached_network_image: ^3.4.1
  connectivity_plus: ^5.0.2
  user_repository:
    path: package/user_repository
  movie_repository:
    path: package/movie_repository
  my_movie_repository:
    path: package/my_movie_repository
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.6
flutter:
  uses-material-design: true
  assets:
     - assets/images/
     - assets/lottie/
     