name: user_repository
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_storage: ^12.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
